docker-deploy/web-app/RSS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('user/', include('user.urls'), name='user'),
    path('ride/', include('ride.urls'), name='ride'),
]

docker-deploy/web-app/ride/urls.py
from django.urls import path
from . import views
from RSS.views import index_view
app_name = 'ride'

urlpatterns = [
    # create new ride request
    path('new/', views.new_ride_view, name='new_ride'),

    # show all rides
    path('view/', views.my_ride_view, name='view_my_ride'),

    # owner revise any ride info
    path('revise/<int:ride_id>', views.revise_ride_info, name='revise_ride'),

    # search any ride in view_my_ride page
    path('search/my/', views.search_my_ride, name='search_my_ride'),

    # ride owner/share user can check driver info
    path('detail/<int:ride_id>', views.ride_detail_view, name='ride_detail'),

    # ride owner delete ride confirm page
    path('delete/<int:ride_id>', views.ride_delete_view, name='delete_ride'),

    # show all shared rides
    path('share/', views.share_ride_view, name='view_share_ride'),

    # search in shared rides
    path('search/share/', views.search_share_ride, name='search_share_ride'),

    # show all open ride request
    path('requests/', views.ride_requests_view, name='ride_requests'),

    # show "ride_id open" ride request information
    path('requests/accept/<int:ride_id>', views.ride_info_view, name='ride_info'),

    # search open rides
    path('requests/search', views.search_ride_request, name='search_ride_request'),

    # join ride
    path('join/<int:ride_id>', views.join_ride, name='join_ride'),

    # cancel my share ride
    path('cancel_share_ride/<int:ride_id>', views.cancel_share_ride, name='cancel_share_ride'),

    # cancel my driver ride
    path('cancel_driver_ride/<int:ride_id>', views.cancel_driver_ride, name='cancel_driver_ride'),

    # complete my driver ride
    path('complete_driver_ride/<int:ride_id>', views.complete_driver_ride, name='complete_driver_ride'),
]

docker-deploy/web-app/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/driver', views.register_driver_view, name='register_driver'),
    path('car/revise/<int:pk>/', views.revise_car_view, name='revise_info'),
    path('car/delete/<int:pk>/', views.delete_car_view.as_view(), name='delete_car'),
    path('car/info/', views.display_car_view, name='display_car'),
    path('driver/delete/', views.cancel_driver_view, name='delete_driver'),
    path('register/captcha/', views.send_email, name='captcha'),
]

docker-deploy/web-app/ride/models.py
from django.db import models
from user.models import RSSUser
from django.utils.timezone import now
from django_fsm import transition, FSMField
# Create your models here.

class RideModel(models.Model):
    departure = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    arrival_time = models.DateTimeField(default=now, verbose_name='Expected arrival time')
    total_passenger = models.IntegerField(default=1)
    can_share = models.BooleanField(default=False, verbose_name='Shared ride')
    vehicle_type = models.CharField(blank=True, default='', verbose_name='Expected vehicle type*')
    sp_info = models.TextField(blank=True, default='', verbose_name='Special Needs*')
    # is_confirmed = models.BooleanField(default=False)
    # is_complete = models.BooleanField(default=False)

    STATUS_CHOICES = [
        ('pending', 'pending'),
        ('confirmed','confirmed'),
        ('complete','complete')
    ]
    status = FSMField(protected=True, choices=STATUS_CHOICES, default='pending')

    pub_time = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(RSSUser, on_delete=models.CASCADE, related_name='owned_rides', null=True)
    driver = models.ForeignKey(RSSUser, on_delete=models.CASCADE, related_name='confirmed_rides', null=True)
    share_user = models.ManyToManyField(RSSUser, related_name='share_rides')

    class Meta:
        ordering = ['-pub_time', 'status']


    @transition(field=status, source='pending', target='confirmed')
    def confirm(self):
        pass

    @transition(field=status, source='confirmed', target='complete')
    def complete(self):
        pass

    @transition(field=status, source='confirmed', target='pending')
    def cancel(self):
        pass

docker-deploy/web-app/ride/forms.py
from datetime import timedelta

from click import style
from django import forms
from .models import RideModel
from django.utils.timezone import now

class NewRideForm(forms.ModelForm):
    class Meta:
        model = RideModel
        exclude = ['owner', 'driver', 'share_user', 'status']
        VEHICLE_CHOICES = [('any','Any'),
                           ('suv','SUV'), 
                           ('pika','Pika'), 
                           ('van','Van'), 
                           ('sedan','Sedan'), 
                           ('sports_car','Sports car'), 
                           ('tank','Tank'), 
                           ('motorcycle','Motorcycle')]
        widgets = {
            'departure': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter departure position'}),
            'destination': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter destination'}),
            'arrival_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local', 'placeholder': 'Enter expected arrival time'},),
            'total_passenger': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter total number of passengers'}),
            'can_share': forms.CheckboxInput(attrs={'class': 'form-check-input', 'style': 'margin-left:2px; margin-top:6px;'}),
            'vehicle_type': forms.Select(attrs={'class': 'form-control'},choices=VEHICLE_CHOICES),
            'sp_info': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter special requirements (Optional)', 'style':'height:38px'}),
        }
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        current_time = now()
        one_week_later = current_time + timedelta(days=7)
        min_time = current_time.strftime('%Y-%m-%dT%H:%M')
        max_time = one_week_later.strftime('%Y-%m-%dT%H:%M')
        # Set arrival time can only be within one weak
        self.fields['arrival_time'].widget.attrs['min'] = min_time
        self.fields['arrival_time'].widget.attrs['max'] = max_time
        self.fields['arrival_time'].input_formats = ['%Y-%m-%dT%H:%M']

    def clean(self):
        status = self.instance.status
        
        cleaned_data = super().clean()
        departure = cleaned_data.get('departure')
        dest = cleaned_data.get('destination')
        total_passenger = cleaned_data.get('total_passenger')
        if status != 'pending':
            raise forms.ValidationError('You cannot revise a confirmed ride.')
        if dest == departure:
            raise forms.ValidationError({'destination': 'Destination and departure place cannot be the same.'})
        if total_passenger <= 0:
            raise forms.ValidationError({'total_passenger': 'Total passenger cannot be non positive number.'})
        return cleaned_data

docker-deploy/web-app/ride/views.py
from traceback import print_tb
import logging
logger = logging.getLogger('django')

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from .forms import NewRideForm
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from .models import RideModel
from user.models import CarModel
from user.models import RSSUser
from RSS.Email import send_message, gmail_authenticate
# Create your views here.
@login_required(login_url='/user/login/')
@require_http_methods(['GET', 'POST'])
def new_ride_view(request):
    if request.method == 'GET':
        form = NewRideForm()
        return render(request, 'ride/new_ride.html', context={'form': form})
    else:
        form = NewRideForm(request.POST)
        if form.is_valid():
            departure = form.cleaned_data.get('departure')
            destination = form.cleaned_data.get('destination')
            arrival_time = form.cleaned_data.get('arrival_time')
            total_passenger = form.cleaned_data.get('total_passenger')
            can_share = form.cleaned_data.get('can_share')
            vehicle_type = form.cleaned_data.get('vehicle_type')
            sp_info = form.cleaned_data.get('sp_info')
            owner = request.user

            RideModel.objects.create(departure=departure,
                                     destination=destination,
                                     arrival_time=arrival_time,
                                     total_passenger=total_passenger,
                                     can_share=can_share,
                                     vehicle_type=vehicle_type,
                                     sp_info=sp_info,
                                     owner=owner)
            logger.info(f"user ({request.user}) try to pub a new ride")
            return render(request, 'ride/new_ride.html', context={'form': form, 'success': True})
        else:
            return render(request, 'ride/new_ride.html', context={'form': form, 'success': False})

@login_required(login_url='/user/login/')
def my_ride_view(request):
    user = request.user
    rides = RideModel.objects.filter(owner__exact=request.user)
    share_rides = RideModel.objects.filter(share_user=request.user)
    driver_rides = RideModel.objects.filter(driver__exact=user)
    return render(request, 'ride/ride.html', context={'rides': rides, 'view_my_ride': True, 'share_rides': share_rides, 'driver_rides': driver_rides})

@login_required(login_url='/user/login/')
@require_http_methods(['GET', 'POST'])
def revise_ride_info(request, ride_id):
    ride = RideModel.objects.get(pk=ride_id)
    if ride.owner != request.user:
        return redirect(reverse('ride:view_my_ride'))
    form = NewRideForm(instance=ride)
    if request.method == 'GET':
        return render(request, 'ride/revise_ride.html', context={'form': form, 'ride': ride})
    else:
        form = NewRideForm(request.POST, instance=ride)
        if form.is_valid():
            form.owner = request.user
            form.save()
            logger.warning(f"user ({request.user}) succeed to revise ride ({ride_id})")
            return render(request, 'ride/revise_ride.html', context={'form': form, 'success': True})
        else:
            return render(request, 'ride/revise_ride.html', context={'form': form, 'success': False})

@login_required(login_url='/user/login/')
@require_http_methods('GET')
def search_my_ride(request):
    q = request.GET.get('q')
    date = request.GET.get('date')
    vehicle = request.GET.get('vehicle')
    ride_query = Q(owner=request.user) & (Q(destination__icontains=q) | Q(departure__icontains=q))
    share_query = Q(share_user=request.user) & (Q(destination__icontains=q) | Q(departure__icontains=q))
    if date:
        ride_query &= Q(arrival_time__date=date)
        share_query &= Q(arrival_time__date=date)
    if vehicle and vehicle != 'any':
        ride_query &= Q(vehicle_type__exact=vehicle)
        share_query &= Q(vehicle_type__exact=vehicle)

    rides = RideModel.objects.filter(ride_query)
    share_rides = RideModel.objects.filter(share_query)
    return render(request, 'ride/ride.html', context={'rides': rides, 'is_search': True, 'share_rides': share_rides, 'view_my_ride': True, 'keyword_request': q, 'date_request': date, 'vehicle_request': vehicle})

@login_required(login_url='/user/login')
def ride_detail_view(request, ride_id):
    ride = RideModel.objects.get(pk=ride_id)
    user = request.user
    if ride.owner != user and not ride.share_user.filter(pk=user.pk).exists():
        return redirect(reverse('ride:view_my_ride'))
    driver = ride.driver
    cars = None
    if driver != None:
        cars = driver.cars.all()

    return render(request, 'ride/ride_info_user_side.html', context={'cars': cars, 'to_guest': True, 'ride':ride})

@login_required(login_url='user/login')
@require_http_methods(['GET','POST'])
def ride_delete_view(request, ride_id):
    ride = RideModel.objects.get(pk=ride_id)
    user = request.user
    if user != ride.owner:
        logger.warning(f"user ({request.user}) try to revise ride ({ride_id}) of user ({ride.owner})")
        return redirect(reverse('ride:view_my_ride'))
    if request.method == 'GET':
        return render(request,'ride/delete_ride.html', context={'ride': ride})
    else:
        ride.delete()
        logger.warning(f"user ({request.user}) succeed to delete ride ({ride_id})")
        return render(request, 'ride/delete_ride.html', context={'success': True})

def share_ride_view(request):
    user = request.user
    # list share ride:
    # 1. ride can be shared
    # 2. ride cannot have been confirmed
    # 3. user cannot be the owner of this ride
    
    query = Q(can_share=True)&Q(status='pending')
    if user.is_authenticated:
        query &= ~Q(owner__exact=user)
        query &= ~Q(share_user__exact=user)
        query &= ~Q(driver__exact=user)
    rides = RideModel.objects.filter(query)

    return render(request, 'ride/share_ride.html', context={'rides':rides, 'view_share_ride': True})

@require_http_methods('GET')
def search_share_ride(request):
    q = request.GET.get('q')
    startTime = request.GET.get('startTime')
    endTime = request.GET.get('endTime')
    user = request.user
    vehicle = request.GET.get('vehicle')
    query = Q(can_share=True)&Q(status='pending')&(Q(destination__icontains=q)|Q(departure__icontains=q)|Q(total_passenger__contains=q))
    if user.is_authenticated:
        query &= ~Q(owner__exact=user)
    if startTime:
        query &= Q(arrival_time__date__gte=startTime)
    if endTime:
        query &= Q(arrival_time__date__lte=endTime)
    if vehicle and vehicle != 'any':
        query &= Q(vehicle_type__exact=vehicle)
    rides = RideModel.objects.filter(query)
    
    return render(request, 'ride/share_ride.html', context={'rides': rides, 'view_share_ride': True, 'keyword_request': q, 'startTime_request': startTime, 'endTime_request': endTime, 'vehicle_request': vehicle})

# help function to get valid ride request query
def get_ride_request_query(request):
    user = request.user
    query = Q(status='pending') & ~Q(owner__exact=user) & ~Q(share_user__exact=user)
    max_passenger = CarModel.objects.get(id=user.id).max_passenger
    query &= Q(total_passenger__lt=max_passenger)
    rides = RideModel.objects.filter(query)
    return rides

@login_required(login_url='/user/login/')
def ride_requests_view(request):
    user = request.user
    if not user.is_driver:
        return redirect(reverse('index'))
    rides = get_ride_request_query(request)
    return render(request, 'ride/ride_request.html', context={'rides': rides,})

@login_required(login_url='/user/login/')
@require_http_methods(['GET', 'POST'])
def ride_info_view(request, ride_id):
    if not request.user.is_driver:
        return redirect(reverse('index'))
    ride = RideModel.objects.get(pk=ride_id)
    if request.method == 'GET':
        show_info_only = request.GET.get('show_info_only')
        return render(request, 'ride/ride_info.html', context={'ride': ride, 'show_info_only': show_info_only})
    else:
        # Update ride driver info
        ride.driver = request.user
        # Update ride to be confirmed
        try:
            ride.confirm()
        except:
            return render(request, 'ride/ride_info.html', context={'ride': ride, 'success': False})
            pass
        ride.save()
        
        logger.warning(f"user ({request.user}) succeed to confirm ride ({ride_id})")

        time = ride.arrival_time.strftime("%Y-%m-%d %H:%M")
        # send email to ride owner
        share_user = [user.username for user in ride.share_user.all() if user.email]
        share_user_str = ', '.join(share_user)
        service = gmail_authenticate()
        send_message(service, "4nanaiiyo@gmail.com", ride.owner.email, "Ride Sharing System",
                     f'<h1>Ride Sharing System Ride Confirmation</h1><div>Your share ride from {ride.departure} to {ride.destination} at {time} has been confirmed.</div><div>Driver: {request.user.username}</div><div>Vehicle Type: {request.user.cars.first().vehicle_type}</div><div>Share users: {share_user_str}</div><br></br><br></br>This is an auto-generated email from Ride Sharing System. Please do not reply.')
        # send email to share user
        share_user_emails = [user.email for user in ride.share_user.all() if user.email]
        for email in share_user_emails:
            # get other share user info
            other_share_users = ride.share_user.exclude(email=email).values_list('username', flat=True)
            other_share_str = ', '.join(other_share_users) if other_share_users else 'None'
            service = gmail_authenticate()
            send_message(service, "4nanaiiyo@gmail.com", email, "Ride Sharing System",

docker-deploy/web-app/ride/templates/ride/ride_info_user_side.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Info</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 20px;
        }
        h3 {
            text-align: left;
            margin-bottom: 20px;
            color: #343a40;
        }
        .table-container {
            max-width: 1000px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .table thead th {
            background-color: #343a40;
            color: white;
        }
        .table tbody tr:hover {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>
    <div class="container table-container">
        {% if to_guest %}
            <h3>Cars Info</h3>
        {% else %}
            <h3>Your Cars Info</h3>
        {% endif %}
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>No.</th>
                    {% if to_guest %}
                    <th>Driver</th>
                    {% endif %}
                    <th>Vehicle Type</th>
                    <th>Vehicle Number</th>
                    <th>Maximum Passenger</th>
                    <th>Special Vehicle Info</th>
                    {% if not to_guest %}
                    <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for car in cars %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    {% if to_guest %}
                    <th>{{ car.user }}</th>
                    {% endif %}
                    <td>{{ car.vehicle_type }}</td>
                    <td>{{ car.vehicle_number }}</td>
                    <td>{{ car.max_passenger }}</td>
                    <td>{{ car.sp_info }}</td>
                    {% if not to_guest %}
                    <td>
                        <a href="{% url 'user:revise_info' car.pk %}" class="btn alert-warning">Revise</a>
                        <a href="{% url 'user:delete_car' car.pk %}" class="btn alert-danger">Delete</a>
                    </td>
                    {% endif %}
                </tr>
                {% empty %}
                    <tr>
                        <td colspan="10" class="text-center">
                            No driver found now.
                            {% comment %} <a href="{% url 'user:register_driver' %}" class="badge alert-primary">Click here</a> to register as a Driver. {% endcomment %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% comment %} <div class="text-right">
        {% if not to_guest %}
        <a href="{% url 'index' %}" class="btn btn-secondary" style="margin-right: 10%; margin-top: 10px">Back</a>
        {% else %}
        <a href="{% url 'ride:view_my_ride' %}" class="btn btn-secondary" style="margin-right: 10%; margin-top: 10px">Back</a>
        {% endif %}
    </div> {% endcomment %}

    <div class="card shadow-sm">
        <div class="card-header bg-secondary text-white text-center">
            <h3>View Ride Request Info</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribute</th>
                        <th scope="col">Details</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Ride Owner</td>
                        <td>{{ ride.owner }}</td>
                    </tr>
                    <tr>
                        <td>Ride Sharers</td>
                        <td>
                            {% for sharers in ride.share_user.all %}
                            {{sharers.username}}(1) {%if not forloop.last%}, {%endif%}
                            {%empty%}
                            No sharers currently
                            {%endfor%}
                        </td>
                    </tr>
                    <tr>
                        <td>Departure</td>
                        <td>{{ ride.departure }}</td>
                    </tr>
                    <tr>
                        <td>Destination</td>
                        <td>{{ ride.destination }}</td>
                    </tr>
                    <tr>
                        <td>Expected Arrival Time</td>
                        <td>{{ ride.arrival_time }}</td>
                    </tr>
                    <tr>
                        <td>total_passenger</td>
                        <td>{{ ride.total_passenger }}</td>
                    </tr>
                    <tr>
                        <td>vehicle type</td>
                        <td>{{ ride.vehicle_type }}</td>
                    </tr>
                    <tr>
                        <td>sp_info</td>
                        <td>{{ ride.sp_info }}</td>
                    </tr>
                </tbody>
            </table>
            </div>
            <!-- Submit Button -->
            
            <script>
                // if POST check SUCCESS
                {% if success %}
                alert("Submit success!");
                // redirect url
                window.location.href = "{% url 'ride:view_my_ride' %}";
                {% endif %}
            </script>
        </div>
    </div>
    <div style="width: 200px; margin: 0 auto; text-align: center;">
        {% if not to_guest %}
        <a href="{% url 'index' %}" class="btn btn-secondary" style="margin-right: 10%; margin-top: 10px">Back</a>
        {% else %}
        <a href="{% url 'ride:view_my_ride' %}" class="btn btn-secondary" style="margin-right: 10%; margin-top: 10px">Back</a>
        {% endif %}
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.4.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

docker-deploy/web-app/ride/templates/ride/share_ride.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ride List</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* Custom styling for the page */
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 20px;
        }
        h3 {
            text-align: left;
            margin-bottom: 20px;
            color: #343a40;
        }
        .table-container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .table thead th {
            background-color: #343a40;
            color: white;
        }
        .table tbody tr:hover {
            background-color: #f1f1f1;
        }
        .btn-secondary[disabled] {
            cursor: not-allowed;
        }
        .text-center button {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container table-container">
        <div class="d-flex justify-content-between align-items-center">
            {% if view_share_ride %}
            <h3>All Share Rides</h3>
            {% endif %}
            <form class="form-inline" action="{% url 'ride:search_share_ride' %}">
{#                Start time search block#}
                <label for="start-date" class="sr-only">startTime</label>
                <input name="startTime" id="start-date" class="form-control mr-sm-2 placeholder-text"
                       type="text" placeholder="Select Start Time"
                       onfocus="(this.type='date')" onblur="(this.type='text')"
                       style="margin-bottom: 20px; width: 150px" value="{{startTime_request}}">

{#                End time search block#}
                <label for="end-date" class="sr-only">endTime</label>
                <input name="endTime" id="end-date" class="form-control mr-sm-2 placeholder-text"
                       type="text" placeholder="Select End Time"
                       onfocus="(this.type='date')" onblur="(this.type='text')"
                       style="margin-bottom: 20px; width: 150px" value="{{endTime_request}}">

{#                text search#}
                <input name="q" class="form-control mr-sm-2" type="search"
                       placeholder="Search" aria-label="Search"
                       style="margin-bottom: 20px; width: 150px" value="{{keyword_request}}">

{#                Car type search added#}
                <select id="vehicle-select" name="vehicle" class="btn btn-outline-primary mr-sm-2" style="margin-bottom: 20px; width: auto">
                    <option value="any" {% if vehicle_request == "any" or not vehicle_request %}selected{% endif %}>Any</option>
                    <option value="suv" {% if vehicle_request == "suv" %}selected{% endif %}>SUV</option>
                    <option value="pika" {% if vehicle_request == "pika" %}selected{% endif %}>Pika</option>
                    <option value="van" {% if vehicle_request == "van" %}selected{% endif %}>Van</option>
                    <option value="sedan" {% if vehicle_request == "sedan" %}selected{% endif %}>Sedan</option>
                    <option value="sports_car" {% if vehicle_request == "sports_car" %}selected{% endif %}>Sports Car</option>
                    <option value="tank" {% if vehicle_request == "tank" %}selected{% endif %}>Tank</option>
                    <option value="motorcycle" {% if vehicle_request == "motorcycle" %}selected{% endif %}>Motorcycle</option>
                </select>

{#                clean search button#}
                <a href="{% url 'ride:view_share_ride' %}" class="btn btn-outline-danger btn-sm mr-sm-2" style="margin-bottom: 20px;">Clean</a>
{#                Submit button#}
                <button class="btn btn-outline-success btn-sm" type="submit" style="margin-bottom: 20px;">Search</button>
            </form>
        </div>
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Departure</th>
                    <th>Destination</th>
                    <th>Arrival Time</th>
                    <th>Vehicle Type</th>
                    <th>Current Total Passengers</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for ride in rides %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ ride.departure }}</td>
                    <td>{{ ride.destination }}</td>
                    <td>{{ ride.arrival_time }}</td>
                    <td>{{ ride.vehicle_type }}</td>
                    <td>{{ ride.total_passenger }}</td>
                    <td>
<!--                        Redirect to a ride join page-->
                    <a href="{% url 'ride:join_ride' ride.pk %}" class="btn btn-primary btn-sm">Join</a>
                    </td>
                </tr>
                {% empty %}
                <!-- Display message if no rides are found -->
                <tr>
                    <td colspan="10" class="text-center">
                        No shared rides found.
                        {% if not is_search %}
                        <a href="{% url 'ride:new_ride' %}" class="badge alert-primary">Click here</a> to register a <strong>new Ride</strong>.
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Add a back button -->
        <div class="text-right">
            <a href="{% url 'index' %}" class="btn btn-secondary" style="margin-right: 10%; margin-top: 10px">Back</a>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>