docker-deploy/web-app/RSS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('user/', include('user.urls'), name='user'),
    path('ride/', include('ride.urls'), name='ride'),
]

docker-deploy/web-app/ride/urls.py
from django.urls import path
from . import views
from RSS.views import index_view
app_name = 'ride'

urlpatterns = [
    # create new ride request
    path('new/', views.new_ride_view, name='new_ride'),

    # show all rides
    path('view/', views.my_ride_view, name='view_my_ride'),

    # owner revise any ride info
    path('revise/<int:ride_id>', views.revise_ride_info, name='revise_ride'),

    # search any ride in view_my_ride page
    path('search/my/', views.search_my_ride, name='search_my_ride'),

    # ride owner/share user can check driver info
    path('detail/<int:ride_id>', views.ride_detail_view, name='ride_detail'),

    # ride owner delete ride confirm page
    path('delete/<int:ride_id>', views.ride_delete_view, name='delete_ride'),

    # show all shared rides
    path('share/', views.share_ride_view, name='view_share_ride'),

    # search in shared rides
    path('search/share/', views.search_share_ride, name='search_share_ride'),

    # show all open ride request
    path('requests/', views.ride_requests_view, name='ride_requests'),

    # show "ride_id open" ride request information
    path('requests/accept/<int:ride_id>', views.ride_info_view, name='ride_info'),

    # search open rides
    path('requests/search', views.search_ride_request, name='search_ride_request'),

    # join ride
    path('join/<int:ride_id>', views.join_ride, name='join_ride'),

    # cancel my share ride
    path('cancel_share_ride/<int:ride_id>', views.cancel_share_ride, name='cancel_share_ride'),

    # cancel my driver ride
    path('cancel_driver_ride/<int:ride_id>', views.cancel_driver_ride, name='cancel_driver_ride'),

    # complete my driver ride
    path('complete_driver_ride/<int:ride_id>', views.complete_driver_ride, name='complete_driver_ride'),
]

docker-deploy/web-app/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/driver', views.register_driver_view, name='register_driver'),
    path('car/revise/<int:pk>/', views.revise_car_view, name='revise_info'),
    path('car/delete/<int:pk>/', views.delete_car_view.as_view(), name='delete_car'),
    path('car/info/', views.display_car_view, name='display_car'),
    path('driver/delete/', views.cancel_driver_view, name='delete_driver'),
    path('register/captcha/', views.send_email, name='captcha'),
]

docker-deploy/web-app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ride Sharing Service</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="bg-light">
    <div class="container">

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="">Ride Sharing Service</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'ride:view_my_ride' %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ride
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'ride:new_ride' %}">New Rides</a>
            <a class="dropdown-item" href="{% url 'ride:view_my_ride' %}">My Rides</a>
            <a class="dropdown-item" href="{% url 'ride:view_share_ride' %}">All Shared Rides</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'user:display_car' %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Driver
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'user:register_driver' %}">Register</a>
            <a class="dropdown-item" href="{% url 'user:display_car' %}">My Car Info</a>
            <a class="dropdown-item" href="{% url 'ride:ride_requests' %}">All Ride Requests</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="" tabindex="-1" aria-disabled="true">About</a>
      </li>
    </ul>
  </div>
</nav>



        <!-- if user authenticated -->
        {% if user.is_authenticated %}
        <div class="alert alert-success text-center mt-3">
            Welcome to RSS website, <strong>{{ user.username }}</strong>!
        </div>

        <!-- if user is not driver -->
        {% if not user.is_driver %}
        <div class="alert alert-info text-center mt-3">
            Want to be a driver?
            <button class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'user:register_driver' %}'">Click here</button>
        </div>

        <!-- if user is driver -->
        {% else %}
        <div class="text-center">
            My cars
            <button class="btn btn-warning btn-sm" onclick="window.location.href='{% url 'user:display_car' %}'" style="margin-right: 20px;">Click here</button>
        </div>
        {% endif %}

        <!-- create rides -->
        <div class="text-center mt-4">
            New share ride:
            <button class="btn btn-info btn-sm" onclick="window.location.href='{% url 'ride:new_ride' %}'">Request</button>
        </div>

        <!-- view rides -->
        <div class="text-center mt-3">
            View ride requests:
            <button class="btn btn-info btn-sm" onclick="window.location.href='{% url 'ride:view_my_ride' %}'">View</button>
        </div>

        <!-- log out -->
        <div class="text-center mt-4">
            <button class="btn btn-danger btn-sm" onclick="window.location.href='{% url 'user:logout' %}'">Sign out</button>
        </div>

        {% else %}

        <!-- not authenticated user -->
        <div class="alert alert-info text-center mt-3">
            Welcome to RSS website.
        </div>

        <!-- login -->
        <div class="text-center mt-3">
            Already have an RSS account?
            <button class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'user:login' %}'">Sign in</button>
        </div>

        <!-- register -->
        <div class="text-center mt-3">
            Want to be a member?
            <button class="btn btn-success btn-sm" onclick="window.location.href='{% url 'user:register' %}'">Sign up</button>
        </div>

        {% endif %}
    </div>

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>